### ISSUE TITLE
not compatible with PCH

### ISSUE THREAD

**Issue by Trass3r** [crosire/blink#20]
because it removes /ZI? At least cl was called without any /Z* debug option

error C2855: commandline option '/Z7' inconsistent with precompiled header

**Comment by crosire** [comment]
PCH is a bit of an issue. Information about the compiled PCH is stored in the application PDB, but it can't be specified on the command-line or else the compiler will attempt to modify it, which won't work while the application is running. blink could copy it to a temporary location and specify that path to workaround this. But what then what happens if the user decides to modify the file generating the PCH? All future compiles would now reference the old PCH data from the application PDB, which no longer makes sense.

**Comment by Trass3r** [comment]
Yeah quite tricky, you could also try to disable PCH but most code out there probably does not compile both ways.

By the way what I tested was the Win32 (GUI) sample project VS generates. That uses PCH by default.

**Comment by ajweeks** [comment]
@crosire It would be great if this limitation was advertised on the readme. Too bad it won't work, I was excited to try this out on my project!

**Comment by crosire** [comment]
blink should still work, it will just take longer to compile a change, since it cannot make use of PCH data.

**Comment by ajweeks** [comment]
It looks like it gets setup fine, but then once I make a code change (in this case to main.cpp) I get the following output:

```
Detected modification to: C:\Code\Flex\Flex\FlexEngine\src\main.cpp
main.cpp
C:\Code\Flex\Flex\FlexEngine\src\main.cpp(1): fatal error C1083: Cannot open include file: 'stdafx.hpp': No such file or directory
Finished compiling "C:\Code\Flex\Flex\FlexEngine\src\main.temp.obj" with code 2.
```

I'm compiling with /ZI, are there any other flags which are necessary? (Edit and Continue for example?)

**Comment by crosire** [comment]
See https://github.com/crosire/blink/issues/32#issuecomment-629705124
