### ISSUE TITLE
Does this work with Visual Studio 2022?

### ISSUE THREAD

**Issue by richardeakin** [crosire/blink#41]
Hi,

I briefly tried firing this up with Visual Studio 2022, the project built fine after doing the auto upgrade and I can run it but haven't been able to get any file changes picked up by the file watcher. So I wanted to check - is this project compatible with VS 2022 /  v143 toolset, or is 2017's toolset still required?

Thanks,
Rich

**Comment by crosire** [comment]
Checked and there was something wrong with the file watcher, which I fixed in b543643f5d2d34d080476013ae430c3ae121408f.

Works with Visual Studio 2022 with that (just note that 2022 like 2019 no longer stores the compile command-line in object files, which means you will have to manually adjust it to match your target project, or otherwise linking can fail due to differences in how the code was produced: https://github.com/crosire/blink/blob/35accf2b4548ea1b27a63f45c66307d7996f4d30/source/blink.cpp#L453).
